# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-13 07:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storenvy',
            name='sale_today',
            field=models.IntegerField(default='0'),
        ),
    ]
